name: flutter_githooks
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/emanuel-braz/flutter_githooks

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.16.0
